
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: backend_container
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3000
    depends_on:
      - backend

